version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.12
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:"VetDB-435"
      - MYSQL_DATABASE:"veterinarioservice"
      - MYSQL_USER:"root"
      - MYSQL_PASSWORD:"VetDB-435"
  apicorepet:
    image: ${DOCKER_REGISTRY}apicorepet
    build:
      context: .
      dockerfile: ApiCorePet/Dockerfile
    depends_on:
    - db
    ports:
    - "8888:80"
    restart: always