version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.12
      - datafiles1:/var/lib/mysql
      restart:always
        
  apicorepet:
    image: ${DOCKER_REGISTRY}apicorepet
    build:
      context: .
      dockerfile: ApiCorePet/Dockerfile
    depends_on:
    - db
    ports:
    -"8888:80"
      restart:always