version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.12
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: VetDB-435
      MYSQL_DATABASE: veterinarioservice
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: VetDB-436
    ports:
      - "3306:3306"
  apicorepet:
    build:
      context: .
      dockerfile: ApiCorePet/Dockerfile
    depends_on:
       - db
    ports:
      - "8888:80"
    links:
      - db
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development